# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170917_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
