# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170917_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
